### ISSUE TITLE
New Theme options

### ISSUE THREAD

**Issue by bungadrum** [sylphenix/Great-IMD-evo#2]
Can you also add a more darker theme variant for example something similar to the greybird dark or a flat remix darkest?

here  are some samples:
https://snipboard.io/Pl2w3m.jpg
https://snipboard.io/QzRWl8.jpg

**Comment by sylphenix** [comment]
I have no plans to add new variants. If you simply want to change the color of the theme, you can try modifying the "color definitions" section at the beginning of the gtk.css file. base_color, darkerA_color and darkerB_color are the main colors. You can adjust these three colors first.
